# Auto-generated by tournament.py — do not edit manually
PLAYER_1_NAME = 'example_bot'
PLAYER_1_PATH = '/Users/navyamehrotra/Documents/Projects/OtherProjects/pokerbots/bots/example_bot'
PLAYER_2_NAME = 'balanced'
PLAYER_2_PATH = '/Users/navyamehrotra/Documents/Projects/OtherProjects/pokerbots/bots/balanced'
GAME_LOG_FILENAME = '/Users/navyamehrotra/Documents/Projects/OtherProjects/pokerbots/logs/match_40'
PLAYER_LOG_SIZE_LIMIT = 524288
ENFORCE_GAME_CLOCK = True
STARTING_GAME_CLOCK = 30.0
BUILD_TIMEOUT = 10
CONNECT_TIMEOUT = 10
NUM_ROUNDS = 1000
STARTING_STACK = 400
BIG_BLIND = 2
SMALL_BLIND = 1
