'''
HopAI Pokerbots - Round-Robin Tournament Runner

Each bot pair plays twice (swapping positions). Rankings by net chips won.
'''
import os
import sys
import subprocess
import re
from itertools import combinations
from datetime import datetime

import database as db

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
ENGINE_DIR = os.path.join(PROJECT_ROOT, 'engine')
BOTS_DIR = os.path.join(PROJECT_ROOT, 'bots')
LOGS_DIR = os.path.join(PROJECT_ROOT, 'logs')

# Match settings — adjust in config.py for experiments
NUM_ROUNDS = 1000
STARTING_STACK = 400
BIG_BLIND = 2
SMALL_BLIND = 1
STARTING_GAME_CLOCK = 30.0
BUILD_TIMEOUT = 10
CONNECT_TIMEOUT = 10
ENFORCE_GAME_CLOCK = True

os.makedirs(LOGS_DIR, exist_ok=True)


def discover_bots():
    '''Scan bots/ directory for valid bot submissions (must have commands.json).'''
    bots = []
    if not os.path.exists(BOTS_DIR):
        return bots
    for entry in sorted(os.listdir(BOTS_DIR)):
        bot_path = os.path.join(BOTS_DIR, entry)
        commands_path = os.path.join(bot_path, 'commands.json')
        if os.path.isdir(bot_path) and os.path.exists(commands_path):
            bots.append({'name': entry, 'path': bot_path})
    return bots


def write_engine_config(bot1_name, bot1_path, bot2_name, bot2_path, log_filename):
    '''Write config.py into the engine directory before running a match.'''
    config = f'''# Auto-generated by tournament.py — do not edit manually
PLAYER_1_NAME = {repr(bot1_name)}
PLAYER_1_PATH = {repr(bot1_path)}
PLAYER_2_NAME = {repr(bot2_name)}
PLAYER_2_PATH = {repr(bot2_path)}
GAME_LOG_FILENAME = {repr(log_filename)}
PLAYER_LOG_SIZE_LIMIT = 524288
ENFORCE_GAME_CLOCK = {ENFORCE_GAME_CLOCK}
STARTING_GAME_CLOCK = {STARTING_GAME_CLOCK}
BUILD_TIMEOUT = {BUILD_TIMEOUT}
CONNECT_TIMEOUT = {CONNECT_TIMEOUT}
NUM_ROUNDS = {NUM_ROUNDS}
STARTING_STACK = {STARTING_STACK}
BIG_BLIND = {BIG_BLIND}
SMALL_BLIND = {SMALL_BLIND}
'''
    with open(os.path.join(ENGINE_DIR, 'config.py'), 'w') as f:
        f.write(config)


def parse_gamelog(log_path, bot1_name, bot2_name):
    '''
    Parse final bankroll deltas from a game log file.
    Returns (delta1, delta2, num_rounds) matched to bot1/bot2 by name.
    '''
    try:
        with open(log_path + '.txt', 'r') as f:
            lines = f.readlines()

        num_rounds = sum(1 for line in lines if line.strip().startswith('Round #'))

        # Find last "Final, Name (delta), Name (delta)" line
        final_line = None
        for line in reversed(lines):
            stripped = line.strip()
            if stripped.startswith('Final'):
                final_line = stripped
                break

        if not final_line:
            return None, None, num_rounds

        # Parse: "Final, BotA (150), BotB (-150)"
        entries = re.findall(r',\s*(\S+)\s*\((-?\d+)\)', final_line)
        deltas = {name: int(delta) for name, delta in entries}

        delta1 = deltas.get(bot1_name)
        delta2 = deltas.get(bot2_name)
        return delta1, delta2, num_rounds

    except (FileNotFoundError, ValueError, IndexError):
        return None, None, 0


def run_match(match_id, bot1, bot2, progress_callback=None):
    '''Run a single match between two bots using the engine subprocess.'''
    # Mark match as running
    with db.get_conn() as conn:
        conn.execute("UPDATE matches SET status='running' WHERE id=?", (match_id,))

    log_filename = os.path.join(LOGS_DIR, f'match_{match_id}')
    write_engine_config(
        bot1['name'], bot1['path'],
        bot2['name'], bot2['path'],
        log_filename
    )

    try:
        result = subprocess.run(
            [sys.executable, 'engine.py'],
            cwd=ENGINE_DIR,
            capture_output=True,
            text=True,
            timeout=NUM_ROUNDS * 15  # generous per-match timeout
        )

        delta1, delta2, num_rounds = parse_gamelog(log_filename, bot1['name'], bot2['name'])

        if delta1 is None or delta2 is None:
            print(f'  [match {match_id}] Could not parse log — marking as error')
            print(f'  engine stdout: {result.stdout[-500:] if result.stdout else "none"}')
            db.update_match(match_id, 0, 0, None, 0, log_filename, 'error')
            return

        if delta1 > delta2:
            winner = bot1['name']
        elif delta2 > delta1:
            winner = bot2['name']
        else:
            winner = None  # draw

        db.update_match(match_id, delta1, delta2, winner, num_rounds, log_filename, 'complete')
        db.update_bot_stats(bot1['name'], delta1, winner == bot1['name'], winner is None)
        db.update_bot_stats(bot2['name'], delta2, winner == bot2['name'], winner is None)

        if progress_callback:
            progress_callback(match_id, bot1['name'], bot2['name'], delta1, delta2, winner)

    except subprocess.TimeoutExpired:
        print(f'  [match {match_id}] Timed out')
        db.update_match(match_id, 0, 0, None, 0, log_filename, 'error')
    except Exception as e:
        print(f'  [match {match_id}] Error: {e}')
        db.update_match(match_id, 0, 0, None, 0, log_filename, 'error')


def run_tournament(progress_callback=None):
    '''
    Run a full round-robin tournament.
    Each unique pair plays twice (with swapped seating positions).
    Rankings determined by cumulative net chips won.
    '''
    db.init_db()

    bots = discover_bots()
    if len(bots) < 2:
        print(f'Need at least 2 bots in {BOTS_DIR}, found {len(bots)}.')
        db.update_tournament_state(status='idle')
        return

    # Register all discovered bots
    for bot in bots:
        db.register_bot(bot['name'], bot['path'])

    # Round-robin: every pair plays twice (swap positions each time)
    pairings = []
    for b1, b2 in combinations(bots, 2):
        pairings.append((b1, b2))
        pairings.append((b2, b1))

    total = len(pairings)
    db.update_tournament_state(
        status='running',
        started_at=datetime.now().isoformat(),
        total_matches=total,
        completed_matches=0
    )

    print(f'\nStarting HopAI Pokerbots Tournament')
    print(f'{len(bots)} bots  |  {total} total matches\n')

    for i, (bot1, bot2) in enumerate(pairings):
        match_id = db.create_match(bot1['name'], bot2['name'])
        print(f'[{i+1}/{total}] {bot1["name"]} vs {bot2["name"]} ...', end=' ', flush=True)
        run_match(match_id, bot1, bot2, progress_callback)
        db.update_tournament_state(completed_matches=i + 1)

    db.update_tournament_state(
        status='complete',
        completed_at=datetime.now().isoformat()
    )

    # Print final standings
    print('\n=== Final Standings ===')
    leaderboard = db.get_leaderboard()
    for rank, row in enumerate(leaderboard, 1):
        print(f'  #{rank}  {row["name"]:20s}  {row["total_delta"]:+6d} chips  '
              f'{row["wins"]}W/{row["losses"]}L/{row["draws"]}D')
    print('\nTournament complete!')


if __name__ == '__main__':
    def print_progress(match_id, b1, b2, d1, d2, winner):
        if winner:
            print(f'{winner} wins  ({d1:+d} / {d2:+d})')
        else:
            print(f'Draw  ({d1:+d} / {d2:+d})')

    run_tournament(print_progress)
